# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0002_auto_20171114_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='language',
            field=models.CharField(choices=[('-', '-'), ('Ru', 'Ru'), ('Es', 'Es')], default='-', max_length=5),
        ),
    ]
