# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:52
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0003_auto_20171114_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/ajanco/tmp/'), upload_to=''),
        ),
    ]
