# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0004_auto_20171115_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='language',
            field=models.CharField(choices=[(b'-', b'-'), (b'Ru', b'Russian'), (b'uk', b'Ukrainian'), (b'Es', b'Spanish'), (b'be', b'Belarusian'), (b'bg', b'Bulgarian')], default=b'-', max_length=5),
        ),
    ]
