# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0005_auto_20171116_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='language',
            field=models.CharField(choices=[(b'-', b'-'), (b'Ru', b'Ru'), (b'az', b'Azerbaijani'), (b'be', b'Belarusian'), (b'bg', b'Bulgarian'), (b'hr', b'Croatian'), (b'cs', b'Czech'), (b'et', b'Estonian'), (b'hu', b'Hungarian'), (b'kk', b'Kazakh'), (b'ky', b'Kyrgyz'), (b'lv', b'Latvian'), (b'lt', b'Lithuanian'), (b'mk', b'Macedonian'), (b'pl', b'Polish'), (b'ro', b'Romanian'), (b'sr', b'Serbian'), (b'sk', b'Slovak'), (b'sl', b'Slovenian'), (b'Es', b'Es'), (b'uk', b'Ukrainian'), (b'uz', b'Uzbek')], default=b'-', max_length=5),
        ),
    ]
